# Generated by Django 4.0.3 on 2022-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(default='Magic man', max_length=350),
            preserve_default=False,
        ),
    ]
