# Generated by Django 4.0.3 on 2022-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size_long_name',
            new_name='size_long',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_short_name',
            new_name='size_short',
        ),
    ]
