# Generated by Django 4.0.3 on 2022-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
