# Generated by Django 4.0.3 on 2022-04-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type'),
        ),
    ]
