# Generated by Django 4.0.3 on 2022-04-06 20:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_ype_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='No image', max_length=255, verbose_name='image'),
        ),
    ]
