# Generated by Django 4.0.3 on 2022-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(default='color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(default='size', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='type', max_length=100),
            preserve_default=False,
        ),
    ]
