# Generated by Django 4.0.3 on 2022-05-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_rating_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='products.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Ok'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], default=0),
        ),
    ]
